// Autogenerated file - DO NOT EDIT
use crate::type_gen::Inner as TypeInner;
use crate::{Kind, Oid, Type};


#[derive(PartialEq, Eq, Clone, Debug, Hash)]
pub enum Inner {
    Binary,
    Varbinary,
    BinaryArray,
    VarbinaryArray,
    MysqlBit,
    MysqlBitArray,
    Rowid,
    RowidArray,
    Int1,
    Int3,
    Mediumint,
    Middleint,
    Longtext,
    Mediumtext,
    Tinytext,
    Longblob,
    Mediumblob,
    Tinyblob,
    MysqlJson,
    Year,
    Uint4,
    Uint4Array,
    Uint8,
    Uint8Array,
    MysqlDate,
    MysqlTime,
    MysqlTimeArray,
    Datetime,
    DatetimeArray,
    MysqlTimestamp,
    MysqlTimestampArray,
    Blob,
    Clob,
    Nclob,
    Bpcharbyte,
    BpcharbyteArray,
    Varcharbyte,
    VarcharbyteArray,
    Tinyint,
    TinyintArray,
}

impl Inner {
    pub fn from_oid(oid: Oid) -> Option<Inner> {
    match oid {
        3383 => Some(Inner::Binary),
        3384 => Some(Inner::Varbinary),
        3385 => Some(Inner::BinaryArray),
        3386 => Some(Inner::VarbinaryArray),
        4655 => Some(Inner::MysqlBit),
        4656 => Some(Inner::MysqlBitArray),
        6123 => Some(Inner::Rowid),
        6124 => Some(Inner::RowidArray),
        7014 => Some(Inner::Int1),
        7015 => Some(Inner::Int3),
        7016 => Some(Inner::Mediumint),
        7017 => Some(Inner::Middleint),
        7018 => Some(Inner::Longtext),
        7019 => Some(Inner::Mediumtext),
        7020 => Some(Inner::Tinytext),
        7021 => Some(Inner::Longblob),
        7022 => Some(Inner::Mediumblob),
        7023 => Some(Inner::Tinyblob),
        7024 => Some(Inner::MysqlJson),
        7025 => Some(Inner::Year),
        7082 => Some(Inner::Uint4),
        7083 => Some(Inner::Uint4Array),
        7084 => Some(Inner::Uint8),
        7085 => Some(Inner::Uint8Array),
        7944 => Some(Inner::MysqlDate),
        7950 => Some(Inner::MysqlTime),
        7951 => Some(Inner::MysqlTimeArray),
        7952 => Some(Inner::Datetime),
        7953 => Some(Inner::DatetimeArray),
        7954 => Some(Inner::MysqlTimestamp),
        7955 => Some(Inner::MysqlTimestampArray),
        8013 => Some(Inner::Blob),
        8014 => Some(Inner::Clob),
        8015 => Some(Inner::Nclob),
        8016 => Some(Inner::Bpcharbyte),
        8017 => Some(Inner::BpcharbyteArray),
        8018 => Some(Inner::Varcharbyte),
        8019 => Some(Inner::VarcharbyteArray),
        8100 => Some(Inner::Tinyint),
        8101 => Some(Inner::TinyintArray),
        _ => None,
    }
    }

    pub fn oid(&self) -> Oid {
        match *self {
            Inner::Binary => 3383,
            Inner::Varbinary => 3384,
            Inner::BinaryArray => 3385,
            Inner::VarbinaryArray => 3386,
            Inner::MysqlBit => 4655,
            Inner::MysqlBitArray => 4656,
            Inner::Rowid => 6123,
            Inner::RowidArray => 6124,
            Inner::Int1 => 7014,
            Inner::Int3 => 7015,
            Inner::Mediumint => 7016,
            Inner::Middleint => 7017,
            Inner::Longtext => 7018,
            Inner::Mediumtext => 7019,
            Inner::Tinytext => 7020,
            Inner::Longblob => 7021,
            Inner::Mediumblob => 7022,
            Inner::Tinyblob => 7023,
            Inner::MysqlJson => 7024,
            Inner::Year => 7025,
            Inner::Uint4 => 7082,
            Inner::Uint4Array => 7083,
            Inner::Uint8 => 7084,
            Inner::Uint8Array => 7085,
            Inner::MysqlDate => 7944,
            Inner::MysqlTime => 7950,
            Inner::MysqlTimeArray => 7951,
            Inner::Datetime => 7952,
            Inner::DatetimeArray => 7953,
            Inner::MysqlTimestamp => 7954,
            Inner::MysqlTimestampArray => 7955,
            Inner::Blob => 8013,
            Inner::Clob => 8014,
            Inner::Nclob => 8015,
            Inner::Bpcharbyte => 8016,
            Inner::BpcharbyteArray => 8017,
            Inner::Varcharbyte => 8018,
            Inner::VarcharbyteArray => 8019,
            Inner::Tinyint => 8100,
            Inner::TinyintArray => 8101,
        }
    }

    pub fn kind(&self) -> &Kind {
        match *self {
            Inner::Binary => {
                &Kind::Simple
            }
            Inner::Varbinary => {
                &Kind::Simple
            }
            Inner::BinaryArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Binary)))
            }
            Inner::VarbinaryArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Varbinary)))
            }
            Inner::MysqlBit => {
                &Kind::Simple
            }
            Inner::MysqlBitArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::MysqlBit)))
            }
            Inner::Rowid => {
                &Kind::Simple
            }
            Inner::RowidArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Rowid)))
            }
            Inner::Int1 => {
                &Kind::Simple
            }
            Inner::Int3 => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Int4)))
            }
            Inner::Mediumint => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Int4)))
            }
            Inner::Middleint => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Int4)))
            }
            Inner::Longtext => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Text)))
            }
            Inner::Mediumtext => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Text)))
            }
            Inner::Tinytext => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Text)))
            }
            Inner::Longblob => {
                &Kind::Domain(Type(TypeInner::Mysql(Inner::Blob)))
            }
            Inner::Mediumblob => {
                &Kind::Domain(Type(TypeInner::Mysql(Inner::Blob)))
            }
            Inner::Tinyblob => {
                &Kind::Domain(Type(TypeInner::Mysql(Inner::Blob)))
            }
            Inner::MysqlJson => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Jsonb)))
            }
            Inner::Year => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Int4)))
            }
            Inner::Uint4 => {
                &Kind::Simple
            }
            Inner::Uint4Array => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Uint4)))
            }
            Inner::Uint8 => {
                &Kind::Simple
            }
            Inner::Uint8Array => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Uint8)))
            }
            Inner::MysqlDate => {
                &Kind::Simple
            }
            Inner::MysqlTime => {
                &Kind::Simple
            }
            Inner::MysqlTimeArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::MysqlTime)))
            }
            Inner::Datetime => {
                &Kind::Simple
            }
            Inner::DatetimeArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Datetime)))
            }
            Inner::MysqlTimestamp => {
                &Kind::Simple
            }
            Inner::MysqlTimestampArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::MysqlTimestamp)))
            }
            Inner::Blob => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Bytea)))
            }
            Inner::Clob => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Text)))
            }
            Inner::Nclob => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Text)))
            }
            Inner::Bpcharbyte => {
                &Kind::Simple
            }
            Inner::BpcharbyteArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Bpcharbyte)))
            }
            Inner::Varcharbyte => {
                &Kind::Simple
            }
            Inner::VarcharbyteArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Varcharbyte)))
            }
            Inner::Tinyint => {
                &Kind::Simple
            }
            Inner::TinyintArray => {
                &Kind::Array(Type(TypeInner::Mysql(Inner::Tinyint)))
            }
        }
    }

    pub fn name(&self) -> &str {
        match *self {
            Inner::Binary => "binary",
            Inner::Varbinary => "varbinary",
            Inner::BinaryArray => "_binary",
            Inner::VarbinaryArray => "_varbinary",
            Inner::MysqlBit => "bit",
            Inner::MysqlBitArray => "_bit",
            Inner::Rowid => "rowid",
            Inner::RowidArray => "_rowid",
            Inner::Int1 => "int1",
            Inner::Int3 => "int3",
            Inner::Mediumint => "mediumint",
            Inner::Middleint => "middleint",
            Inner::Longtext => "longtext",
            Inner::Mediumtext => "mediumtext",
            Inner::Tinytext => "tinytext",
            Inner::Longblob => "longblob",
            Inner::Mediumblob => "mediumblob",
            Inner::Tinyblob => "tinyblob",
            Inner::MysqlJson => "json",
            Inner::Year => "year",
            Inner::Uint4 => "uint4",
            Inner::Uint4Array => "_uint4",
            Inner::Uint8 => "uint8",
            Inner::Uint8Array => "_uint8",
            Inner::MysqlDate => "date",
            Inner::MysqlTime => "time",
            Inner::MysqlTimeArray => "_time",
            Inner::Datetime => "datetime",
            Inner::DatetimeArray => "_datetime",
            Inner::MysqlTimestamp => "timestamp",
            Inner::MysqlTimestampArray => "_timestamp",
            Inner::Blob => "blob",
            Inner::Clob => "clob",
            Inner::Nclob => "nclob",
            Inner::Bpcharbyte => "bpcharbyte",
            Inner::BpcharbyteArray => "_bpcharbyte",
            Inner::Varcharbyte => "varcharbyte",
            Inner::VarcharbyteArray => "_varcharbyte",
            Inner::Tinyint => "tinyint",
            Inner::TinyintArray => "_tinyint",
        }
    }

    pub fn schema(&self) -> &str {
        match *self {
            Inner::Binary => "sys",
            Inner::Varbinary => "sys",
            Inner::BinaryArray => "sys",
            Inner::VarbinaryArray => "sys",
            Inner::MysqlBit => "sys",
            Inner::MysqlBitArray => "sys",
            Inner::Rowid => "sys",
            Inner::RowidArray => "sys",
            Inner::Int1 => "sys",
            Inner::Int3 => "sys",
            Inner::Mediumint => "sys",
            Inner::Middleint => "sys",
            Inner::Longtext => "sys",
            Inner::Mediumtext => "sys",
            Inner::Tinytext => "sys",
            Inner::Longblob => "sys",
            Inner::Mediumblob => "sys",
            Inner::Tinyblob => "sys",
            Inner::MysqlJson => "sys",
            Inner::Year => "sys",
            Inner::Uint4 => "sys",
            Inner::Uint4Array => "sys",
            Inner::Uint8 => "sys",
            Inner::Uint8Array => "sys",
            Inner::MysqlDate => "sys",
            Inner::MysqlTime => "sys",
            Inner::MysqlTimeArray => "sys",
            Inner::Datetime => "sys",
            Inner::DatetimeArray => "sys",
            Inner::MysqlTimestamp => "sys",
            Inner::MysqlTimestampArray => "sys",
            Inner::Blob => "sys",
            Inner::Clob => "sys",
            Inner::Nclob => "sys",
            Inner::Bpcharbyte => "sys",
            Inner::BpcharbyteArray => "sys",
            Inner::Varcharbyte => "sys",
            Inner::VarcharbyteArray => "sys",
            Inner::Tinyint => "sys",
            Inner::TinyintArray => "sys",
        }
    }
}
