// Autogenerated file - DO NOT EDIT
use crate::type_gen::Inner as TypeInner;
use crate::{Kind, Oid, Type};


#[derive(PartialEq, Eq, Clone, Debug, Hash)]
pub enum Inner {
    Rowid,
    RowidArray,
    Urowid,
    UrowidArray,
    Dsinterval,
    DsintervalArray,
    Yminterval,
    YmintervalArray,
    Blob,
    Clob,
    Nclob,
    Bpcharbyte,
    BpcharbyteArray,
    Varcharbyte,
    VarcharbyteArray,
    OraDate,
    OraDateArray,
    Bfile,
    BfileArray,
    Tinyint,
    TinyintArray,
}

impl Inner {
    pub fn from_oid(oid: Oid) -> Option<Inner> {
    match oid {
        6123 => Some(Inner::Rowid),
        6124 => Some(Inner::RowidArray),
        6125 => Some(Inner::Urowid),
        6126 => Some(Inner::UrowidArray),
        7000 => Some(Inner::Dsinterval),
        7001 => Some(Inner::DsintervalArray),
        7002 => Some(Inner::Yminterval),
        7003 => Some(Inner::YmintervalArray),
        8013 => Some(Inner::Blob),
        8014 => Some(Inner::Clob),
        8015 => Some(Inner::Nclob),
        8016 => Some(Inner::Bpcharbyte),
        8017 => Some(Inner::BpcharbyteArray),
        8018 => Some(Inner::Varcharbyte),
        8019 => Some(Inner::VarcharbyteArray),
        8020 => Some(Inner::OraDate),
        8021 => Some(Inner::OraDateArray),
        8078 => Some(Inner::Bfile),
        8079 => Some(Inner::BfileArray),
        8100 => Some(Inner::Tinyint),
        8101 => Some(Inner::TinyintArray),
        _ => None,
    }
    }

    pub fn oid(&self) -> Oid {
        match *self {
            Inner::Rowid => 6123,
            Inner::RowidArray => 6124,
            Inner::Urowid => 6125,
            Inner::UrowidArray => 6126,
            Inner::Dsinterval => 7000,
            Inner::DsintervalArray => 7001,
            Inner::Yminterval => 7002,
            Inner::YmintervalArray => 7003,
            Inner::Blob => 8013,
            Inner::Clob => 8014,
            Inner::Nclob => 8015,
            Inner::Bpcharbyte => 8016,
            Inner::BpcharbyteArray => 8017,
            Inner::Varcharbyte => 8018,
            Inner::VarcharbyteArray => 8019,
            Inner::OraDate => 8020,
            Inner::OraDateArray => 8021,
            Inner::Bfile => 8078,
            Inner::BfileArray => 8079,
            Inner::Tinyint => 8100,
            Inner::TinyintArray => 8101,
        }
    }

    pub fn kind(&self) -> &Kind {
        match *self {
            Inner::Rowid => {
                &Kind::Simple
            }
            Inner::RowidArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::Rowid)))
            }
            Inner::Urowid => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Varchar)))
            }
            Inner::UrowidArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::Urowid)))
            }
            Inner::Dsinterval => {
                &Kind::Simple
            }
            Inner::DsintervalArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::Dsinterval)))
            }
            Inner::Yminterval => {
                &Kind::Simple
            }
            Inner::YmintervalArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::Yminterval)))
            }
            Inner::Blob => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Bytea)))
            }
            Inner::Clob => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Text)))
            }
            Inner::Nclob => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Text)))
            }
            Inner::Bpcharbyte => {
                &Kind::Simple
            }
            Inner::BpcharbyteArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::Bpcharbyte)))
            }
            Inner::Varcharbyte => {
                &Kind::Simple
            }
            Inner::VarcharbyteArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::Varcharbyte)))
            }
            Inner::OraDate => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::Timestamp)))
            }
            Inner::OraDateArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::OraDate)))
            }
            Inner::Bfile => {
                &Kind::Simple
            }
            Inner::BfileArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::Bfile)))
            }
            Inner::Tinyint => {
                &Kind::Simple
            }
            Inner::TinyintArray => {
                &Kind::Array(Type(TypeInner::Oracle(Inner::Tinyint)))
            }
        }
    }

    pub fn name(&self) -> &str {
        match *self {
            Inner::Rowid => "rowid",
            Inner::RowidArray => "_rowid",
            Inner::Urowid => "urowid",
            Inner::UrowidArray => "_urowid",
            Inner::Dsinterval => "dsinterval",
            Inner::DsintervalArray => "_dsinterval",
            Inner::Yminterval => "yminterval",
            Inner::YmintervalArray => "_yminterval",
            Inner::Blob => "blob",
            Inner::Clob => "clob",
            Inner::Nclob => "nclob",
            Inner::Bpcharbyte => "bpcharbyte",
            Inner::BpcharbyteArray => "_bpcharbyte",
            Inner::Varcharbyte => "varcharbyte",
            Inner::VarcharbyteArray => "_varcharbyte",
            Inner::OraDate => "date",
            Inner::OraDateArray => "_date",
            Inner::Bfile => "bfile",
            Inner::BfileArray => "_bfile",
            Inner::Tinyint => "tinyint",
            Inner::TinyintArray => "_tinyint",
        }
    }

    pub fn schema(&self) -> &str {
        match *self {
            Inner::Rowid => "pg_catalog",
            Inner::RowidArray => "pg_catalog",
            Inner::Urowid => "pg_catalog",
            Inner::UrowidArray => "pg_catalog",
            Inner::Dsinterval => "sys",
            Inner::DsintervalArray => "sys",
            Inner::Yminterval => "sys",
            Inner::YmintervalArray => "sys",
            Inner::Blob => "pg_catalog",
            Inner::Clob => "pg_catalog",
            Inner::Nclob => "pg_catalog",
            Inner::Bpcharbyte => "sys",
            Inner::BpcharbyteArray => "sys",
            Inner::Varcharbyte => "sys",
            Inner::VarcharbyteArray => "sys",
            Inner::OraDate => "sys",
            Inner::OraDateArray => "sys",
            Inner::Bfile => "pg_catalog",
            Inner::BfileArray => "pg_catalog",
            Inner::Tinyint => "pg_catalog",
            Inner::TinyintArray => "pg_catalog",
        }
    }
}
