// Autogenerated file - DO NOT EDIT
use crate::type_gen::Inner as TypeInner;
use crate::{Kind, Oid, Type};


#[derive(PartialEq, Eq, Clone, Debug, Hash)]
pub enum Inner {
    Uniqueidentifier,
    Binary,
    BinaryArray,
    Varbinary,
    VarbinaryArray,
    Tinyint,
    TinyintArray,
    Nchar,
    NcharArray,
    Nvarchar,
    NvarcharArray,
    Rowversion,
    RowversionArray,
    Smalldatetime,
    SmalldatetimeArray,
    SqlServerMoney,
    SqlServerMoneyArray,
    SysnameArray,
    SqlVariant,
    SqlVariantArray,
    Sysname,
    Datetime2Array,
    Datetime2,
    SqlServerDate,
    SqlServerTime,
    SqlServerDateArray,
    SqlServerTimeArray,
    Datetime,
    DatetimeArray,
    SqlServerBit,
    SqlServerBitArray,
    Bpcharbyte,
    BpcharbyteArray,
    Varcharbyte,
    VarcharbyteArray,
    SysLsnArray,
    SysLsn,
    UniqueidentifierArray,
}

impl Inner {
    pub fn from_oid(oid: Oid) -> Option<Inner> {
    match oid {
        4193 => Some(Inner::Uniqueidentifier),
        5022 => Some(Inner::Binary),
        5023 => Some(Inner::BinaryArray),
        5024 => Some(Inner::Varbinary),
        5025 => Some(Inner::VarbinaryArray),
        5026 => Some(Inner::Tinyint),
        5027 => Some(Inner::TinyintArray),
        5039 => Some(Inner::Nchar),
        5040 => Some(Inner::NcharArray),
        5041 => Some(Inner::Nvarchar),
        5042 => Some(Inner::NvarcharArray),
        5043 => Some(Inner::Rowversion),
        5044 => Some(Inner::RowversionArray),
        5045 => Some(Inner::Smalldatetime),
        5046 => Some(Inner::SmalldatetimeArray),
        5069 => Some(Inner::SqlServerMoney),
        5070 => Some(Inner::SqlServerMoneyArray),
        6080 => Some(Inner::SysnameArray),
        6661 => Some(Inner::SqlVariant),
        6662 => Some(Inner::SqlVariantArray),
        7141 => Some(Inner::Sysname),
        7680 => Some(Inner::Datetime2Array),
        7690 => Some(Inner::Datetime2),
        7754 => Some(Inner::SqlServerDate),
        7755 => Some(Inner::SqlServerTime),
        7764 => Some(Inner::SqlServerDateArray),
        7765 => Some(Inner::SqlServerTimeArray),
        7881 => Some(Inner::Datetime),
        7891 => Some(Inner::DatetimeArray),
        7915 => Some(Inner::SqlServerBit),
        7916 => Some(Inner::SqlServerBitArray),
        8016 => Some(Inner::Bpcharbyte),
        8017 => Some(Inner::BpcharbyteArray),
        8018 => Some(Inner::Varcharbyte),
        8019 => Some(Inner::VarcharbyteArray),
        12464 => Some(Inner::SysLsnArray),
        12465 => Some(Inner::SysLsn),
        12476 => Some(Inner::UniqueidentifierArray),
        _ => None,
    }
    }

    pub fn oid(&self) -> Oid {
        match *self {
            Inner::Uniqueidentifier => 4193,
            Inner::Binary => 5022,
            Inner::BinaryArray => 5023,
            Inner::Varbinary => 5024,
            Inner::VarbinaryArray => 5025,
            Inner::Tinyint => 5026,
            Inner::TinyintArray => 5027,
            Inner::Nchar => 5039,
            Inner::NcharArray => 5040,
            Inner::Nvarchar => 5041,
            Inner::NvarcharArray => 5042,
            Inner::Rowversion => 5043,
            Inner::RowversionArray => 5044,
            Inner::Smalldatetime => 5045,
            Inner::SmalldatetimeArray => 5046,
            Inner::SqlServerMoney => 5069,
            Inner::SqlServerMoneyArray => 5070,
            Inner::SysnameArray => 6080,
            Inner::SqlVariant => 6661,
            Inner::SqlVariantArray => 6662,
            Inner::Sysname => 7141,
            Inner::Datetime2Array => 7680,
            Inner::Datetime2 => 7690,
            Inner::SqlServerDate => 7754,
            Inner::SqlServerTime => 7755,
            Inner::SqlServerDateArray => 7764,
            Inner::SqlServerTimeArray => 7765,
            Inner::Datetime => 7881,
            Inner::DatetimeArray => 7891,
            Inner::SqlServerBit => 7915,
            Inner::SqlServerBitArray => 7916,
            Inner::Bpcharbyte => 8016,
            Inner::BpcharbyteArray => 8017,
            Inner::Varcharbyte => 8018,
            Inner::VarcharbyteArray => 8019,
            Inner::SysLsnArray => 12464,
            Inner::SysLsn => 12465,
            Inner::UniqueidentifierArray => 12476,
        }
    }

    pub fn kind(&self) -> &Kind {
        match *self {
            Inner::Uniqueidentifier => {
                &Kind::Simple
            }
            Inner::Binary => {
                &Kind::Simple
            }
            Inner::BinaryArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Binary)))
            }
            Inner::Varbinary => {
                &Kind::Simple
            }
            Inner::VarbinaryArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Varbinary)))
            }
            Inner::Tinyint => {
                &Kind::Simple
            }
            Inner::TinyintArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Tinyint)))
            }
            Inner::Nchar => {
                &Kind::Simple
            }
            Inner::NcharArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Nchar)))
            }
            Inner::Nvarchar => {
                &Kind::Simple
            }
            Inner::NvarcharArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Nvarchar)))
            }
            Inner::Rowversion => {
                &Kind::Simple
            }
            Inner::RowversionArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Rowversion)))
            }
            Inner::Smalldatetime => {
                &Kind::Simple
            }
            Inner::SmalldatetimeArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Smalldatetime)))
            }
            Inner::SqlServerMoney => {
                &Kind::Simple
            }
            Inner::SqlServerMoneyArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::SqlServerMoney)))
            }
            Inner::SysnameArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Sysname)))
            }
            Inner::SqlVariant => {
                &Kind::Simple
            }
            Inner::SqlVariantArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::SqlVariant)))
            }
            Inner::Sysname => {
                &Kind::Domain(Type(TypeInner::SqlServer(Inner::Nvarchar)))
            }
            Inner::Datetime2Array => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Datetime2)))
            }
            Inner::Datetime2 => {
                &Kind::Simple
            }
            Inner::SqlServerDate => {
                &Kind::Simple
            }
            Inner::SqlServerTime => {
                &Kind::Simple
            }
            Inner::SqlServerDateArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::SqlServerDate)))
            }
            Inner::SqlServerTimeArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::SqlServerTime)))
            }
            Inner::Datetime => {
                &Kind::Simple
            }
            Inner::DatetimeArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Datetime)))
            }
            Inner::SqlServerBit => {
                &Kind::Simple
            }
            Inner::SqlServerBitArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::SqlServerBit)))
            }
            Inner::Bpcharbyte => {
                &Kind::Simple
            }
            Inner::BpcharbyteArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Bpcharbyte)))
            }
            Inner::Varcharbyte => {
                &Kind::Simple
            }
            Inner::VarcharbyteArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Varcharbyte)))
            }
            Inner::SysLsnArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::SysLsn)))
            }
            Inner::SysLsn => {
                &Kind::Domain(Type(TypeInner::Pg(crate::pg_type_gen::Inner::PgLsn)))
            }
            Inner::UniqueidentifierArray => {
                &Kind::Array(Type(TypeInner::SqlServer(Inner::Uniqueidentifier)))
            }
        }
    }

    pub fn name(&self) -> &str {
        match *self {
            Inner::Uniqueidentifier => "uniqueidentifier",
            Inner::Binary => "binary",
            Inner::BinaryArray => "_binary",
            Inner::Varbinary => "varbinary",
            Inner::VarbinaryArray => "_varbinary",
            Inner::Tinyint => "tinyint",
            Inner::TinyintArray => "_tinyint",
            Inner::Nchar => "nchar",
            Inner::NcharArray => "_nchar",
            Inner::Nvarchar => "nvarchar",
            Inner::NvarcharArray => "_nvarchar",
            Inner::Rowversion => "rowversion",
            Inner::RowversionArray => "_rowversion",
            Inner::Smalldatetime => "smalldatetime",
            Inner::SmalldatetimeArray => "_smalldatetime",
            Inner::SqlServerMoney => "money",
            Inner::SqlServerMoneyArray => "_money",
            Inner::SysnameArray => "_sysname",
            Inner::SqlVariant => "sql_variant",
            Inner::SqlVariantArray => "_sql_variant",
            Inner::Sysname => "sysname",
            Inner::Datetime2Array => "_datetime2",
            Inner::Datetime2 => "datetime2",
            Inner::SqlServerDate => "date",
            Inner::SqlServerTime => "time",
            Inner::SqlServerDateArray => "_date",
            Inner::SqlServerTimeArray => "_time",
            Inner::Datetime => "datetime",
            Inner::DatetimeArray => "_datetime",
            Inner::SqlServerBit => "bit",
            Inner::SqlServerBitArray => "_bit",
            Inner::Bpcharbyte => "bpcharbyte",
            Inner::BpcharbyteArray => "_bpcharbyte",
            Inner::Varcharbyte => "varcharbyte",
            Inner::VarcharbyteArray => "_varcharbyte",
            Inner::SysLsnArray => "_sys_lsn",
            Inner::SysLsn => "sys_lsn",
            Inner::UniqueidentifierArray => "_uniqueidentifier",
        }
    }

    pub fn schema(&self) -> &str {
        match *self {
            Inner::Uniqueidentifier => "sys",
            Inner::Binary => "sys",
            Inner::BinaryArray => "sys",
            Inner::Varbinary => "sys",
            Inner::VarbinaryArray => "sys",
            Inner::Tinyint => "sys",
            Inner::TinyintArray => "sys",
            Inner::Nchar => "sys",
            Inner::NcharArray => "sys",
            Inner::Nvarchar => "sys",
            Inner::NvarcharArray => "sys",
            Inner::Rowversion => "sys",
            Inner::RowversionArray => "sys",
            Inner::Smalldatetime => "sys",
            Inner::SmalldatetimeArray => "sys",
            Inner::SqlServerMoney => "sys",
            Inner::SqlServerMoneyArray => "sys",
            Inner::SysnameArray => "sys",
            Inner::SqlVariant => "sys",
            Inner::SqlVariantArray => "sys",
            Inner::Sysname => "sys",
            Inner::Datetime2Array => "sys",
            Inner::Datetime2 => "sys",
            Inner::SqlServerDate => "sys",
            Inner::SqlServerTime => "sys",
            Inner::SqlServerDateArray => "sys",
            Inner::SqlServerTimeArray => "sys",
            Inner::Datetime => "sys",
            Inner::DatetimeArray => "sys",
            Inner::SqlServerBit => "sys",
            Inner::SqlServerBitArray => "sys",
            Inner::Bpcharbyte => "sys",
            Inner::BpcharbyteArray => "sys",
            Inner::Varcharbyte => "sys",
            Inner::VarcharbyteArray => "sys",
            Inner::SysLsnArray => "sys_catalog",
            Inner::SysLsn => "sys_catalog",
            Inner::UniqueidentifierArray => "sys",
        }
    }
}
