// Autogenerated file - DO NOT EDIT
use std::sync::Arc;

use crate::{Kind, Oid, Type};

#[derive(PartialEq, Eq, Debug, Hash)]
pub struct Other {
    pub name: String,
    pub oid: Oid,
    pub kind: Kind,
    pub schema: String,
}

#[derive(PartialEq, Eq, Clone, Debug, Hash)]
pub enum Inner {
    Pg(crate::pg_type_gen::Inner),
    Mysql(crate::mysql_type_gen::Inner),
    Other(Arc<Other>),
}

impl Inner {
    pub fn oid(&self) -> Oid {
        match *self {
            Inner::Pg(ref inner) => inner.oid(),
            Inner::Mysql(ref inner) => inner.oid(),
            Inner::Other(ref u) => u.oid,
        }
    }

    pub fn kind(&self) -> &Kind {
        match *self {
            Inner::Pg(ref inner) => inner.kind(),
            Inner::Mysql(ref inner) => inner.kind(),
            Inner::Other(ref u) => &u.kind,
        }
    }

    pub fn name(&self) -> &str {
        match *self {
            Inner::Pg(ref inner) => inner.name(),
            Inner::Mysql(ref inner) => inner.name(),
            Inner::Other(ref u) => &u.name,
        }
    }

    pub fn schema(&self) -> &str {
        match *self {
            Inner::Pg(ref inner) => inner.schema(),
            Inner::Mysql(ref inner) => inner.schema(),
            Inner::Other(ref u) => &u.schema,
        }
    }
}
impl Type {
    /// BOOL - boolean, &#39;true&#39;/&#39;false&#39;
    pub const BOOL: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Bool));

    /// BYTEA - variable-length string, binary values escaped
    pub const BYTEA: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Bytea));

    /// CHAR - single character
    pub const CHAR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Char));

    /// NAME - 63-byte type for storing system identifiers
    pub const NAME: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Name));

    /// INT8 - ~18 digit integer, 8-byte storage
    pub const INT8: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int8));

    /// INT2 - -32 thousand to 32 thousand, 2-byte storage
    pub const INT2: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int2));

    /// INT2VECTOR - array of int2, used in system tables
    pub const INT2_VECTOR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int2Vector));

    /// INT4 - -2 billion to 2 billion integer, 4-byte storage
    pub const INT4: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int4));

    /// REGPROC - registered procedure
    pub const REGPROC: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regproc));

    /// TEXT - variable-length string, no limit specified
    pub const TEXT: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Text));

    /// OID - object identifier&#40;oid&#41;, maximum 4 billion
    pub const OID: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Oid));

    /// TID - &#40;block, offset&#41;, physical location of tuple
    pub const TID: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Tid));

    /// XID - transaction id
    pub const XID: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Xid));

    /// CID - command identifier type, sequence in transaction id
    pub const CID: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Cid));

    /// OIDVECTOR - array of oids, used in system tables
    pub const OID_VECTOR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::OidVector));

    /// PG_DDL_COMMAND - internal type for passing CollectedCommand
    pub const PG_DDL_COMMAND: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgDdlCommand));

    /// JSON - JSON stored as text
    pub const JSON: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Json));

    /// XML - XML content
    pub const XML: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Xml));

    /// XML&#91;&#93;
    pub const XML_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::XmlArray));

    /// PG_NODE_TREE - string representing an internal node tree
    pub const PG_NODE_TREE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgNodeTree));

    /// JSON&#91;&#93;
    pub const JSON_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::JsonArray));

    /// TABLE_AM_HANDLER
    pub const TABLE_AM_HANDLER: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TableAmHandler));

    /// XID8&#91;&#93;
    pub const XID8_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Xid8Array));

    /// INDEX_AM_HANDLER - pseudo-type for the result of an index AM handler function
    pub const INDEX_AM_HANDLER: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::IndexAmHandler));

    /// POINT - geometric point &#39;&#40;x, y&#41;&#39;
    pub const POINT: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Point));

    /// LSEG - geometric line segment &#39;&#40;pt1,pt2&#41;&#39;
    pub const LSEG: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Lseg));

    /// PATH - geometric path &#39;&#40;pt1,...&#41;&#39;
    pub const PATH: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Path));

    /// BOX - geometric box &#39;&#40;lower left,upper right&#41;&#39;
    pub const BOX: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Box));

    /// POLYGON - geometric polygon &#39;&#40;pt1,...&#41;&#39;
    pub const POLYGON: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Polygon));

    /// LINE - geometric line
    pub const LINE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Line));

    /// LINE&#91;&#93;
    pub const LINE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::LineArray));

    /// CIDR - network IP address/netmask, network address
    pub const CIDR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Cidr));

    /// CIDR&#91;&#93;
    pub const CIDR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::CidrArray));

    /// FLOAT4 - single-precision floating point number, 4-byte storage
    pub const FLOAT4: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Float4));

    /// FLOAT8 - double-precision floating point number, 8-byte storage
    pub const FLOAT8: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Float8));

    /// UNKNOWN - pseudo-type representing an undetermined type
    pub const UNKNOWN: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Unknown));

    /// CIRCLE - geometric circle &#39;&#40;center,radius&#41;&#39;
    pub const CIRCLE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Circle));

    /// CIRCLE&#91;&#93;
    pub const CIRCLE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::CircleArray));

    /// MACADDR8 - XX:XX:XX:XX:XX:XX:XX:XX, MAC address
    pub const MACADDR8: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Macaddr8));

    /// MACADDR8&#91;&#93;
    pub const MACADDR8_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Macaddr8Array));

    /// MONEY - monetary amounts, &#36;d,ddd.cc
    pub const MONEY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Money));

    /// MONEY&#91;&#93;
    pub const MONEY_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::MoneyArray));

    /// MACADDR - XX:XX:XX:XX:XX:XX, MAC address
    pub const MACADDR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Macaddr));

    /// INET - IP address/netmask, host address, netmask optional
    pub const INET: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Inet));

    /// BOOL&#91;&#93;
    pub const BOOL_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::BoolArray));

    /// BYTEA&#91;&#93;
    pub const BYTEA_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::ByteaArray));

    /// CHAR&#91;&#93;
    pub const CHAR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::CharArray));

    /// NAME&#91;&#93;
    pub const NAME_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::NameArray));

    /// INT2&#91;&#93;
    pub const INT2_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int2Array));

    /// INT2VECTOR&#91;&#93;
    pub const INT2_VECTOR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int2VectorArray));

    /// INT4&#91;&#93;
    pub const INT4_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int4Array));

    /// REGPROC&#91;&#93;
    pub const REGPROC_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::RegprocArray));

    /// TEXT&#91;&#93;
    pub const TEXT_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TextArray));

    /// TID&#91;&#93;
    pub const TID_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TidArray));

    /// XID&#91;&#93;
    pub const XID_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::XidArray));

    /// CID&#91;&#93;
    pub const CID_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::CidArray));

    /// OIDVECTOR&#91;&#93;
    pub const OID_VECTOR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::OidVectorArray));

    /// BPCHAR&#91;&#93;
    pub const BPCHAR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::BpcharArray));

    /// VARCHAR&#91;&#93;
    pub const VARCHAR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::VarcharArray));

    /// INT8&#91;&#93;
    pub const INT8_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int8Array));

    /// POINT&#91;&#93;
    pub const POINT_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PointArray));

    /// LSEG&#91;&#93;
    pub const LSEG_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::LsegArray));

    /// PATH&#91;&#93;
    pub const PATH_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PathArray));

    /// BOX&#91;&#93;
    pub const BOX_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::BoxArray));

    /// FLOAT4&#91;&#93;
    pub const FLOAT4_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Float4Array));

    /// FLOAT8&#91;&#93;
    pub const FLOAT8_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Float8Array));

    /// POLYGON&#91;&#93;
    pub const POLYGON_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PolygonArray));

    /// OID&#91;&#93;
    pub const OID_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::OidArray));

    /// ACLITEM - access control list
    pub const ACLITEM: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Aclitem));

    /// ACLITEM&#91;&#93;
    pub const ACLITEM_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::AclitemArray));

    /// MACADDR&#91;&#93;
    pub const MACADDR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::MacaddrArray));

    /// INET&#91;&#93;
    pub const INET_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::InetArray));

    /// BPCHAR - char&#40;length&#41;, blank-padded string, fixed storage length
    pub const BPCHAR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Bpchar));

    /// VARCHAR - varchar&#40;length&#41;, non-blank-padded string, variable storage length
    pub const VARCHAR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Varchar));

    /// DATE - date
    pub const DATE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Date));

    /// TIME - time of day
    pub const TIME: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Time));

    /// TIMESTAMP - date and time
    pub const TIMESTAMP: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Timestamp));

    /// TIMESTAMP&#91;&#93;
    pub const TIMESTAMP_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TimestampArray));

    /// DATE&#91;&#93;
    pub const DATE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::DateArray));

    /// TIME&#91;&#93;
    pub const TIME_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TimeArray));

    /// TIMESTAMPTZ - date and time with time zone
    pub const TIMESTAMPTZ: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Timestamptz));

    /// TIMESTAMPTZ&#91;&#93;
    pub const TIMESTAMPTZ_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::TimestamptzArray));

    /// INTERVAL - &#64; &lt;number&gt; &lt;units&gt;, time interval
    pub const INTERVAL: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Interval));

    /// INTERVAL&#91;&#93;
    pub const INTERVAL_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::IntervalArray));

    /// NUMERIC&#91;&#93;
    pub const NUMERIC_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::NumericArray));

    /// CSTRING&#91;&#93;
    pub const CSTRING_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::CstringArray));

    /// TIMETZ - time of day with time zone
    pub const TIMETZ: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Timetz));

    /// TIMETZ&#91;&#93;
    pub const TIMETZ_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TimetzArray));

    /// BIT - fixed-length bit string
    pub const BIT: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Bit));

    /// BIT&#91;&#93;
    pub const BIT_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::BitArray));

    /// VARBIT - variable-length bit string
    pub const VARBIT: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Varbit));

    /// VARBIT&#91;&#93;
    pub const VARBIT_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::VarbitArray));

    /// NUMERIC - numeric&#40;precision, decimal&#41;, arbitrary precision number
    pub const NUMERIC: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Numeric));

    /// REFCURSOR - reference to cursor &#40;portal name&#41;
    pub const REFCURSOR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Refcursor));

    /// REFCURSOR&#91;&#93;
    pub const REFCURSOR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::RefcursorArray));

    /// REGPROCEDURE - registered procedure &#40;with args&#41;
    pub const REGPROCEDURE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regprocedure));

    /// REGOPER - registered operator
    pub const REGOPER: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regoper));

    /// REGOPERATOR - registered operator &#40;with args&#41;
    pub const REGOPERATOR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regoperator));

    /// REGCLASS - registered class
    pub const REGCLASS: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regclass));

    /// REGTYPE - registered type
    pub const REGTYPE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regtype));

    /// REGPROCEDURE&#91;&#93;
    pub const REGPROCEDURE_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::RegprocedureArray));

    /// REGOPER&#91;&#93;
    pub const REGOPER_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::RegoperArray));

    /// REGOPERATOR&#91;&#93;
    pub const REGOPERATOR_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::RegoperatorArray));

    /// REGCLASS&#91;&#93;
    pub const REGCLASS_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::RegclassArray));

    /// REGTYPE&#91;&#93;
    pub const REGTYPE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::RegtypeArray));

    /// RECORD - pseudo-type representing any composite type
    pub const RECORD: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Record));

    /// CSTRING - C-style string
    pub const CSTRING: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Cstring));

    /// ANY - pseudo-type representing any type
    pub const ANY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Any));

    /// ANYARRAY - pseudo-type representing a polymorphic array type
    pub const ANYARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Anyarray));

    /// VOID - pseudo-type for the result of a function with no real result
    pub const VOID: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Void));

    /// TRIGGER - pseudo-type for the result of a trigger function
    pub const TRIGGER: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Trigger));

    /// LANGUAGE_HANDLER - pseudo-type for the result of a language handler function
    pub const LANGUAGE_HANDLER: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::LanguageHandler));

    /// INTERNAL - pseudo-type representing an internal data structure
    pub const INTERNAL: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Internal));

    /// ANYELEMENT - pseudo-type representing a polymorphic base type
    pub const ANYELEMENT: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Anyelement));

    /// RECORD&#91;&#93;
    pub const RECORD_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::RecordArray));

    /// ANYNONARRAY - pseudo-type representing a polymorphic base type that is not an array
    pub const ANYNONARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Anynonarray));

    /// TXID_SNAPSHOT&#91;&#93;
    pub const TXID_SNAPSHOT_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::TxidSnapshotArray));

    /// UUID - UUID datatype
    pub const UUID: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Uuid));

    /// UUID&#91;&#93;
    pub const UUID_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::UuidArray));

    /// TXID_SNAPSHOT - txid snapshot
    pub const TXID_SNAPSHOT: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TxidSnapshot));

    /// FDW_HANDLER - pseudo-type for the result of an FDW handler function
    pub const FDW_HANDLER: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::FdwHandler));

    /// PG_LSN - PostgreSQL LSN datatype
    pub const PG_LSN: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgLsn));

    /// PG_LSN&#91;&#93;
    pub const PG_LSN_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgLsnArray));

    /// TSM_HANDLER - pseudo-type for the result of a tablesample method function
    pub const TSM_HANDLER: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TsmHandler));

    /// PG_NDISTINCT - multivariate ndistinct coefficients
    pub const PG_NDISTINCT: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgNdistinct));

    /// PG_DEPENDENCIES - multivariate dependencies
    pub const PG_DEPENDENCIES: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgDependencies));

    /// ANYENUM - pseudo-type representing a polymorphic base type that is an enum
    pub const ANYENUM: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Anyenum));

    /// TSVECTOR - text representation for text search
    pub const TS_VECTOR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TsVector));

    /// TSQUERY - query representation for text search
    pub const TSQUERY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Tsquery));

    /// GTSVECTOR - GiST index internal text representation for text search
    pub const GTS_VECTOR: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::GtsVector));

    /// TSVECTOR&#91;&#93;
    pub const TS_VECTOR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TsVectorArray));

    /// GTSVECTOR&#91;&#93;
    pub const GTS_VECTOR_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::GtsVectorArray));

    /// TSQUERY&#91;&#93;
    pub const TSQUERY_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TsqueryArray));

    /// REGCONFIG - registered text search configuration
    pub const REGCONFIG: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regconfig));

    /// REGCONFIG&#91;&#93;
    pub const REGCONFIG_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::RegconfigArray));

    /// REGDICTIONARY - registered text search dictionary
    pub const REGDICTIONARY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regdictionary));

    /// REGDICTIONARY&#91;&#93;
    pub const REGDICTIONARY_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::RegdictionaryArray));

    /// JSONB - Binary JSON
    pub const JSONB: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Jsonb));

    /// JSONB&#91;&#93;
    pub const JSONB_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::JsonbArray));

    /// ANYRANGE - pseudo-type representing a range over a polymorphic base type
    pub const ANY_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::AnyRange));

    /// EVENT_TRIGGER - pseudo-type for the result of an event trigger function
    pub const EVENT_TRIGGER: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::EventTrigger));

    /// INT4RANGE - range of integers
    pub const INT4_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int4Range));

    /// INT4RANGE&#91;&#93;
    pub const INT4_RANGE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int4RangeArray));

    /// NUMRANGE - range of numerics
    pub const NUM_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::NumRange));

    /// NUMRANGE&#91;&#93;
    pub const NUM_RANGE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::NumRangeArray));

    /// TSRANGE - range of timestamps without time zone
    pub const TS_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TsRange));

    /// TSRANGE&#91;&#93;
    pub const TS_RANGE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TsRangeArray));

    /// TSTZRANGE - range of timestamps with time zone
    pub const TSTZ_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TstzRange));

    /// TSTZRANGE&#91;&#93;
    pub const TSTZ_RANGE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TstzRangeArray));

    /// DATERANGE - range of dates
    pub const DATE_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::DateRange));

    /// DATERANGE&#91;&#93;
    pub const DATE_RANGE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::DateRangeArray));

    /// INT8RANGE - range of bigints
    pub const INT8_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int8Range));

    /// INT8RANGE&#91;&#93;
    pub const INT8_RANGE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int8RangeArray));

    /// JSONPATH - JSON path
    pub const JSONPATH: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Jsonpath));

    /// JSONPATH&#91;&#93;
    pub const JSONPATH_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::JsonpathArray));

    /// REGNAMESPACE - registered namespace
    pub const REGNAMESPACE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regnamespace));

    /// REGNAMESPACE&#91;&#93;
    pub const REGNAMESPACE_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::RegnamespaceArray));

    /// REGROLE - registered role
    pub const REGROLE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regrole));

    /// REGROLE&#91;&#93;
    pub const REGROLE_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::RegroleArray));

    /// REGCOLLATION - registered collation
    pub const REGCOLLATION: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Regcollation));

    /// REGCOLLATION&#91;&#93;
    pub const REGCOLLATION_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::RegcollationArray));

    /// INT4MULTIRANGE - multirange of integers
    pub const INT4MULTI_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int4multiRange));

    /// NUMMULTIRANGE - multirange of numerics
    pub const NUMMULTI_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::NummultiRange));

    /// TSMULTIRANGE - multirange of timestamps without time zone
    pub const TSMULTI_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TsmultiRange));

    /// TSTZMULTIRANGE - multirange of timestamps with time zone
    pub const TSTZMULTI_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::TstzmultiRange));

    /// DATEMULTIRANGE - multirange of dates
    pub const DATEMULTI_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::DatemultiRange));

    /// INT8MULTIRANGE - multirange of bigints
    pub const INT8MULTI_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Int8multiRange));

    /// ANYMULTIRANGE - pseudo-type representing a polymorphic base type that is a multirange
    pub const ANYMULTI_RANGE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::AnymultiRange));

    /// ANYCOMPATIBLEMULTIRANGE - pseudo-type representing a multirange over a polymorphic common type
    pub const ANYCOMPATIBLEMULTI_RANGE: Type = Type(Inner::Pg(
        crate::pg_type_gen::Inner::AnycompatiblemultiRange,
    ));

    /// PG_BRIN_BLOOM_SUMMARY - BRIN bloom summary
    pub const PG_BRIN_BLOOM_SUMMARY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::PgBrinBloomSummary));

    /// PG_BRIN_MINMAX_MULTI_SUMMARY - BRIN minmax-multi summary
    pub const PG_BRIN_MINMAX_MULTI_SUMMARY: Type = Type(Inner::Pg(
        crate::pg_type_gen::Inner::PgBrinMinmaxMultiSummary,
    ));

    /// PG_MCV_LIST - multivariate MCV list
    pub const PG_MCV_LIST: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgMcvList));

    /// PG_SNAPSHOT - snapshot
    pub const PG_SNAPSHOT: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgSnapshot));

    /// PG_SNAPSHOT&#91;&#93;
    pub const PG_SNAPSHOT_ARRAY: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::PgSnapshotArray));

    /// XID8 - full transaction id
    pub const XID8: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Xid8));

    /// ANYCOMPATIBLE - pseudo-type representing a polymorphic common type
    pub const ANYCOMPATIBLE: Type = Type(Inner::Pg(crate::pg_type_gen::Inner::Anycompatible));

    /// ANYCOMPATIBLEARRAY - pseudo-type representing an array of polymorphic common type elements
    pub const ANYCOMPATIBLEARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::Anycompatiblearray));

    /// ANYCOMPATIBLENONARRAY - pseudo-type representing a polymorphic common type that is not an array
    pub const ANYCOMPATIBLENONARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::Anycompatiblenonarray));

    /// ANYCOMPATIBLERANGE - pseudo-type representing a range over a polymorphic common type
    pub const ANYCOMPATIBLE_RANGE: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::AnycompatibleRange));

    /// INT4MULTIRANGE&#91;&#93;
    pub const INT4MULTI_RANGE_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::Int4multiRangeArray));

    /// NUMMULTIRANGE&#91;&#93;
    pub const NUMMULTI_RANGE_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::NummultiRangeArray));

    /// TSMULTIRANGE&#91;&#93;
    pub const TSMULTI_RANGE_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::TsmultiRangeArray));

    /// TSTZMULTIRANGE&#91;&#93;
    pub const TSTZMULTI_RANGE_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::TstzmultiRangeArray));

    /// DATEMULTIRANGE&#91;&#93;
    pub const DATEMULTI_RANGE_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::DatemultiRangeArray));

    /// INT8MULTIRANGE&#91;&#93;
    pub const INT8MULTI_RANGE_ARRAY: Type =
        Type(Inner::Pg(crate::pg_type_gen::Inner::Int8multiRangeArray));

    /// BOOL - boolean, &#39;true&#39;/&#39;false&#39;
    pub const MYSQL_BOOL: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Bool));

    /// BYTEA - variable-length string, binary values escaped
    pub const MYSQL_BYTEA: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Bytea));

    /// CHAR - single character
    pub const MYSQL_CHAR: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Char));

    /// NAME - 63-byte type for storing system identifiers
    pub const MYSQL_NAME: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Name));

    /// INT8 - ~18 digit integer, 8-byte storage
    pub const MYSQL_INT8: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Int8));

    /// INT2 - -32 thousand to 32 thousand, 2-byte storage
    pub const MYSQL_INT2: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Int2));

    /// INT4 - -2 billion to 2 billion integer, 4-byte storage
    pub const MYSQL_INT4: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Int4));

    /// TEXT - variable-length string, no limit specified
    pub const MYSQL_TEXT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Text));

    /// OID - object identifier&#40;oid&#41;, maximum 4 billion
    pub const MYSQL_OID: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Oid));

    /// JSON - JSON stored as text
    pub const MYSQL_JSON: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Json));

    /// JSON&#91;&#93;
    pub const MYSQL_JSON_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::JsonArray));

    /// POINT - geometric point &#39;&#40;x, y&#41;&#39;
    pub const MYSQL_POINT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Point));

    /// FLOAT4 - single-precision floating point number, 4-byte storage
    pub const MYSQL_FLOAT4: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Float4));

    /// FLOAT8 - double-precision floating point number, 8-byte storage
    pub const MYSQL_FLOAT8: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Float8));

    /// UNKNOWN - pseudo-type representing an undetermined type
    pub const MYSQL_UNKNOWN: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Unknown));

    /// MONEY - monetary amounts, &#36;d,ddd.cc
    pub const MYSQL_MONEY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Money));

    /// MONEY&#91;&#93;
    pub const MYSQL_MONEY_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::MoneyArray));

    /// BOOL&#91;&#93;
    pub const MYSQL_BOOL_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::BoolArray));

    /// BYTEA&#91;&#93;
    pub const MYSQL_BYTEA_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::ByteaArray));

    /// CHAR&#91;&#93;
    pub const MYSQL_CHAR_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::CharArray));

    /// NAME&#91;&#93;
    pub const MYSQL_NAME_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::NameArray));

    /// INT2&#91;&#93;
    pub const MYSQL_INT2_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Int2Array));

    /// INT4&#91;&#93;
    pub const MYSQL_INT4_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Int4Array));

    /// TEXT&#91;&#93;
    pub const MYSQL_TEXT_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::TextArray));

    /// BPCHAR&#91;&#93;
    pub const MYSQL_BPCHAR_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::BpcharArray));

    /// VARCHAR&#91;&#93;
    pub const MYSQL_VARCHAR_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::VarcharArray));

    /// INT8&#91;&#93;
    pub const MYSQL_INT8_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Int8Array));

    /// POINT&#91;&#93;
    pub const MYSQL_POINT_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::PointArray));

    /// FLOAT4&#91;&#93;
    pub const MYSQL_FLOAT4_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::Float4Array));

    /// FLOAT8&#91;&#93;
    pub const MYSQL_FLOAT8_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::Float8Array));

    /// OID&#91;&#93;
    pub const MYSQL_OID_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::OidArray));

    /// BPCHAR - char&#40;length&#41;, blank-padded string, fixed storage length
    pub const MYSQL_BPCHAR: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Bpchar));

    /// VARCHAR - varchar&#40;length&#41;, non-blank-padded string, variable storage length
    pub const MYSQL_VARCHAR: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Varchar));

    /// DATE - date
    pub const MYSQL_DATE: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Date));

    /// TIME - time of day
    pub const MYSQL_TIME: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Time));

    /// TIMESTAMP - date and time
    pub const MYSQL_TIMESTAMP: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Timestamp));

    /// TIMESTAMP&#91;&#93;
    pub const MYSQL_TIMESTAMP_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::TimestampArray));

    /// DATE&#91;&#93;
    pub const MYSQL_DATE_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::DateArray));

    /// TIME&#91;&#93;
    pub const MYSQL_TIME_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::TimeArray));

    /// TIMESTAMPTZ - date and time with time zone
    pub const MYSQL_TIMESTAMPTZ: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::Timestamptz));

    /// TIMESTAMPTZ&#91;&#93;
    pub const MYSQL_TIMESTAMPTZ_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::TimestamptzArray));

    /// NUMERIC&#91;&#93;
    pub const MYSQL_NUMERIC_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::NumericArray));

    /// TIMETZ - time of day with time zone
    pub const MYSQL_TIMETZ: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Timetz));

    /// TIMETZ&#91;&#93;
    pub const MYSQL_TIMETZ_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::TimetzArray));

    /// BIT - fixed-length bit string
    pub const MYSQL_BIT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Bit));

    /// BIT&#91;&#93;
    pub const MYSQL_BIT_ARRAY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::BitArray));

    /// NUMERIC - numeric&#40;precision, decimal&#41;, arbitrary precision number
    pub const MYSQL_NUMERIC: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Numeric));

    /// REFCURSOR - reference to cursor &#40;portal name&#41;
    pub const MYSQL_REFCURSOR: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Refcursor));

    /// REFCURSOR&#91;&#93;
    pub const MYSQL_REFCURSOR_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::RefcursorArray));

    /// sys.binary - Kingbase MySQL-compatible type
    pub const MYSQL_BINARY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Binary));

    /// sys.varbinary - Kingbase MySQL-compatible type
    pub const MYSQL_VARBINARY: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Varbinary));

    /// sys._binary - Kingbase MySQL-compatible array type
    pub const MYSQL_BINARY_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::BinaryArray));

    /// sys._varbinary - Kingbase MySQL-compatible array type
    pub const MYSQL_VARBINARY_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::VarbinaryArray));

    /// JSONB - Binary JSON
    pub const MYSQL_JSONB: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Jsonb));

    /// JSONB&#91;&#93;
    pub const MYSQL_JSONB_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::JsonbArray));

    /// sys.bit - Kingbase MySQL-compatible type
    pub const MYSQL_SYS_BIT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::MysqlBit));

    /// sys._bit - Kingbase MySQL-compatible array type
    pub const MYSQL_SYS_BIT_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::MysqlBitArray));

    /// sys.rowid - Kingbase MySQL-compatible type
    pub const MYSQL_ROWID: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Rowid));

    /// sys._rowid - Kingbase MySQL-compatible array type
    pub const MYSQL_ROWID_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::RowidArray));

    /// sys.int1 - Kingbase MySQL-compatible type
    pub const MYSQL_INT1: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Int1));

    /// sys.int3 - Kingbase MySQL-compatible domain
    pub const MYSQL_INT3: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Int3));

    /// sys.mediumint - Kingbase MySQL-compatible domain
    pub const MYSQL_MEDIUMINT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Mediumint));

    /// sys.middleint - Kingbase MySQL-compatible domain
    pub const MYSQL_MIDDLEINT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Middleint));

    /// sys.longtext - Kingbase MySQL-compatible domain
    pub const MYSQL_LONGTEXT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Longtext));

    /// sys.mediumtext - Kingbase MySQL-compatible domain
    pub const MYSQL_MEDIUMTEXT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Mediumtext));

    /// sys.tinytext - Kingbase MySQL-compatible domain
    pub const MYSQL_TINYTEXT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Tinytext));

    /// sys.longblob - Kingbase MySQL-compatible domain
    pub const MYSQL_LONGBLOB: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Longblob));

    /// sys.mediumblob - Kingbase MySQL-compatible domain
    pub const MYSQL_MEDIUMBLOB: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Mediumblob));

    /// sys.tinyblob - Kingbase MySQL-compatible domain
    pub const MYSQL_TINYBLOB: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Tinyblob));

    /// sys.json - Kingbase MySQL-compatible domain
    pub const MYSQL_SYS_JSON: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::MysqlJson));

    /// sys.year - Kingbase MySQL-compatible domain
    pub const MYSQL_YEAR: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Year));

    /// sys.uint4 - Kingbase MySQL-compatible type
    pub const MYSQL_UINT4: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Uint4));

    /// sys._uint4 - Kingbase MySQL-compatible array type
    pub const MYSQL_UINT4_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::Uint4Array));

    /// sys.uint8 - Kingbase MySQL-compatible type
    pub const MYSQL_UINT8: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Uint8));

    /// sys._uint8 - Kingbase MySQL-compatible array type
    pub const MYSQL_UINT8_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::Uint8Array));

    /// sys.date - Kingbase MySQL-compatible type
    pub const MYSQL_SYS_DATE: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::MysqlDate));

    /// sys.time - Kingbase MySQL-compatible type
    pub const MYSQL_SYS_TIME: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::MysqlTime));

    /// sys._time - Kingbase MySQL-compatible array type
    pub const MYSQL_SYS_TIME_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::MysqlTimeArray));

    /// sys.datetime - Kingbase MySQL-compatible type
    pub const MYSQL_DATETIME: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Datetime));

    /// sys._datetime - Kingbase MySQL-compatible array type
    pub const MYSQL_DATETIME_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::DatetimeArray));

    /// sys.timestamp - Kingbase MySQL-compatible type
    pub const MYSQL_SYS_TIMESTAMP: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::MysqlTimestamp));

    /// sys._timestamp - Kingbase MySQL-compatible array type
    pub const MYSQL_SYS_TIMESTAMP_ARRAY: Type = Type(Inner::Mysql(
        crate::mysql_type_gen::Inner::MysqlTimestampArray,
    ));

    /// sys.blob - Kingbase MySQL-compatible domain
    pub const MYSQL_BLOB: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Blob));

    /// sys.clob - Kingbase MySQL-compatible domain
    pub const MYSQL_CLOB: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Clob));

    /// sys.nclob - Kingbase MySQL-compatible domain
    pub const MYSQL_NCLOB: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Nclob));

    /// sys.bpcharbyte - Kingbase MySQL-compatible type
    pub const MYSQL_BPCHARBYTE: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Bpcharbyte));

    /// sys._bpcharbyte - Kingbase MySQL-compatible array type
    pub const MYSQL_BPCHARBYTE_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::BpcharbyteArray));

    /// sys.varcharbyte - Kingbase MySQL-compatible type
    pub const MYSQL_VARCHARBYTE: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::Varcharbyte));

    /// sys._varcharbyte - Kingbase MySQL-compatible array type
    pub const MYSQL_VARCHARBYTE_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::VarcharbyteArray));

    /// sys.tinyint - Kingbase MySQL-compatible type
    pub const MYSQL_TINYINT: Type = Type(Inner::Mysql(crate::mysql_type_gen::Inner::Tinyint));

    /// sys._tinyint - Kingbase MySQL-compatible array type
    pub const MYSQL_TINYINT_ARRAY: Type =
        Type(Inner::Mysql(crate::mysql_type_gen::Inner::TinyintArray));
    /// MySQL SQL alias SMALLINT for the 2-byte integer type
    pub const MYSQL_SMALLINT: Type = Type::MYSQL_INT2;

    /// MySQL SQL alias SMALLINT[] for the 2-byte integer array type
    pub const MYSQL_SMALLINT_ARRAY: Type = Type::MYSQL_INT2_ARRAY;

    /// MySQL SQL alias INTEGER for the 4-byte integer type
    pub const MYSQL_INTEGER: Type = Type::MYSQL_INT4;

    /// MySQL SQL alias INTEGER[] for the 4-byte integer array type
    pub const MYSQL_INTEGER_ARRAY: Type = Type::MYSQL_INT4_ARRAY;

    /// MySQL SQL alias INT for the 4-byte integer type
    pub const MYSQL_INT: Type = Type::MYSQL_INT4;

    /// MySQL SQL alias INT[] for the 4-byte integer array type
    pub const MYSQL_INT_ARRAY: Type = Type::MYSQL_INT4_ARRAY;

    /// MySQL SQL alias BIGINT for the 8-byte integer type
    pub const MYSQL_BIGINT: Type = Type::MYSQL_INT8;

    /// MySQL SQL alias BIGINT[] for the 8-byte integer array type
    pub const MYSQL_BIGINT_ARRAY: Type = Type::MYSQL_INT8_ARRAY;

    /// MySQL SQL alias FLOAT for the single-precision floating point type
    pub const MYSQL_FLOAT: Type = Type::MYSQL_FLOAT4;

    /// MySQL SQL alias FLOAT[] for the single-precision floating point array type
    pub const MYSQL_FLOAT_ARRAY: Type = Type::MYSQL_FLOAT4_ARRAY;

    /// MySQL SQL alias DOUBLE for the double-precision floating point type
    pub const MYSQL_DOUBLE: Type = Type::MYSQL_FLOAT8;

    /// MySQL SQL alias DOUBLE[] for the double-precision floating point array type
    pub const MYSQL_DOUBLE_ARRAY: Type = Type::MYSQL_FLOAT8_ARRAY;

    /// MySQL SQL alias DECIMAL for the arbitrary precision numeric type
    pub const MYSQL_DECIMAL: Type = Type::MYSQL_NUMERIC;

    /// MySQL SQL alias DECIMAL[] for the arbitrary precision numeric array type
    pub const MYSQL_DECIMAL_ARRAY: Type = Type::MYSQL_NUMERIC_ARRAY;

    /// MySQL SQL alias DEC for the arbitrary precision numeric type
    pub const MYSQL_DEC: Type = Type::MYSQL_NUMERIC;

    /// MySQL SQL alias FIXED for the arbitrary precision numeric type
    pub const MYSQL_FIXED: Type = Type::MYSQL_NUMERIC;

    /// MySQL SQL alias BOOLEAN for the boolean type
    pub const MYSQL_BOOLEAN: Type = Type::MYSQL_BOOL;

    /// MySQL SQL alias BOOLEAN[] for the boolean array type
    pub const MYSQL_BOOLEAN_ARRAY: Type = Type::MYSQL_BOOL_ARRAY;
}
